### ISSUE TITLE
Testing with lnbits v1.0.0-rc5

### ISSUE THREAD

**Issue by Amperstrand** [lnbits/usermanager#24]
I see that many of the extensions have been updated to the upcoming v1.0.0 release, but not the usermanager.

This is the error I get when trying to install usermanager v0.4.1:

```
 2024-11-14 12:08:30.00 | INFO | lnbits.core.extensions.models:download_archive:455 | Downloading extension usermanager (0.4.1).
 2024-11-14 12:08:30.84 | INFO | lnbits.core.extensions.models:extract_archive:488 | Extracting extension usermanager (0.4.1).
 2024-11-14 12:08:30.94 | INFO | lnbits.core.extensions.models:extract_archive:526 | Extension User Manager (0.4.1) extracted.
 2024-11-14 12:08:31.00 | ERROR | lnbits.core.helpers:migrate_extension_database:30 | cannot import name 'get_key_type' from 'lnbits.decorators' (/app/lnbits/decorators.py)
 2024-11-14 12:08:31.00 | WARNING | lnbits.core.views.extension_api:api_install_extension:88 | Cannot import module for extension 'usermanager'.
 Traceback (most recent call last):
   File "/app/lnbits/core/helpers.py", line 27, in migrate_extension_database
     ext_migrations = importlib.import_module(f"{ext.module_name}.migrations")
   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "/app/lnbits/extensions/usermanager/__init__.py", line 23, in <module>
     from .views_api import *  # noqa
   File "/app/lnbits/extensions/usermanager/views_api.py", line 11, in <module>
     from lnbits.decorators import (
 ImportError: cannot import name 'get_key_type' from 'lnbits.decorators' (/app/lnbits/decorators.py)
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/app/lnbits/core/views/extension_api.py", line 85, in api_install_extension
     extension = await install_extension(ext_info)
   File "/app/lnbits/core/extensions/extension_manager.py", line 32, in install_extension
     await migrate_extension_database(ext_info, db_version)
   File "/app/lnbits/core/helpers.py", line 31, in migrate_extension_database
     raise ImportError(f"Cannot import module for extension '{ext.id}'.") from exc
 ImportError: Cannot import module for extension 'usermanager'.
 2024-11-14 12:08:31.13 | ERROR | lnbits.exceptions:http_exception_handler:103 | HTTPException 500: Failed to install extension 'usermanager'.(0.4.1).
```

**Comment by dni** [comment]
i think usermanager will be phased out, @motorina0 whats the consensus on that topic, do you know?

**Comment by motorina0** [comment]
Core covers all the functionality that used to be in `usermanager` extension.
See: https://github.com/lnbits/lnbits/pull/2777

`usermanager` will be retired

**Comment by warioishere** [comment]
what if I used usermanager before? I upgraded to lnbits 1.0.0 and jst found out usermanager doesnt work anymore.
A lot of people used usermanager to manage accounts for tip bots and so on. How do I restore those accounts now?

Our tipbot on matrix which used user manager doesnt work anymore.

**Comment by warioishere** [comment]
could you pls make usermanager work again? Its a real pain that our tipbot is down :(

**Comment by warioishere** [comment]
I cannot choose the rc1 of 1.0:

![Image](https://github.com/user-attachments/assets/26514748-45f7-4b5a-bbc7-ad5437e4c6ee)

how do I enable to use release candiates?
